### ISSUE TITLE
首頁Card的圖示要不要灰階?

### ISSUE THREAD

**Issue by bestian** [3dw/freemath#68]
全灰階看起來有點單調?
<img width="1019" alt="截圖 2024-07-02 晚上8 17 28" src="https://github.com/3dw/freemath/assets/109048/49fde81f-9ec4-45d0-86cd-d4a11b9365d6">

灰階38%的效果
<img width="1019" alt="截圖 2024-07-02 晚上8 16 47" src="https://github.com/3dw/freemath/assets/109048/51424dcf-5e59-49d9-9f9b-adf54de692fc">

無灰階的效果
<img width="1019" alt="截圖 2024-07-03 上午8 16 19" src="https://github.com/3dw/freemath/assets/109048/f4ecfd0c-fe7a-4364-a267-c091418ab596">

**Comment by Tofuswang** [comment]
penpot 檔案裡的灰階 icon 只是用來協助排版的工具（因為 penpot 模板裡沒有彩色 icon 的模板 Orz）
我同意在這個場景下使用全彩的 icon
